export type FormalDemoBranchCaseId = 'aster' | 'outsourcing' | 'capstone';

export interface FormalDemoBranchChoice {
  id: string;
  title: string;
  routeLabel: string;
  consequence: string;
  answer: string;
  nextStepId: string | null;
  impactModuleIds: string[];
}

export interface FormalDemoBranchStep {
  id: string;
  moduleId: string;
  prompt: string;
  context: string;
  choices: FormalDemoBranchChoice[];
}

export interface FormalDemoBranchScenario {
  caseId: FormalDemoBranchCaseId;
  domainLabel: string;
  routeTitle: string;
  introduction: string;
  completionMessage: string;
  startStepId: string;
  steps: Record<string, FormalDemoBranchStep>;
}

const FORMAL_DEMO_BRANCH_SCENARIOS: Record<FormalDemoBranchCaseId, FormalDemoBranchScenario> = {
  aster: {
    caseId: 'aster',
    domainLabel: '现场服务 / 安全与合规',
    routeTitle: '峰会通行风险处置路线',
    introduction: '峰会现场的效率、安全和追责会互相影响。先确定最不能接受的失败，再展开对应处置路线。',
    completionMessage: '通行项目的首轮关键模块已经形成可复核路线；这不是项目终点，报告会保留后续仍需确认的内容。',
    startStepId: 'aster_priority',
    steps: {
      aster_priority: {
        id: 'aster_priority',
        moduleId: 'service_journey',
        prompt: '峰会当天最不能接受的失败是什么？',
        context: '这个判断会决定先优化现场流程、审批责任，还是事后追溯。',
        choices: [
          {
            id: 'peak_queue',
            title: '高峰排队失控',
            routeLabel: '高峰通行',
            consequence: '先处理凭证、设备和临时来访的分流，避免所有异常都堵在门岗。',
            answer: '峰会当天最不能接受的是入口排队失控。先保证高峰核验速度，并把凭证异常、设备故障和临时来访分流处理。',
            nextStepId: 'aster_exception',
            impactModuleIds: ['exception', 'risk', 'scope'],
          },
          {
            id: 'unauthorized_access',
            title: '无权限人员被放行',
            routeLabel: '授权边界',
            consequence: '先厘清临时放行权和复核责任，再调整门岗操作流程。',
            answer: '峰会当天最不能接受的是无权限人员被放行。需要先明确临时放行的批准人、复核条件和责任记录。',
            nextStepId: 'aster_permissions',
            impactModuleIds: ['roles', 'audit', 'exception'],
          },
          {
            id: 'missing_trace',
            title: '异常发生后无法追责',
            routeLabel: '审计追踪',
            consequence: '先定义记录粒度和查询权限，再决定现场操作必须留下哪些证据。',
            answer: '峰会当天最不能接受的是异常发生后无法还原过程。每次核验、人工放行和信息修改都要能追溯到人员、时间和原因。',
            nextStepId: 'aster_audit',
            impactModuleIds: ['audit', 'roles', 'risk'],
          },
        ],
      },
      aster_exception: {
        id: 'aster_exception',
        moduleId: 'exception',
        prompt: '凭证过期或临时来访时，现场优先采用哪种处置方式？',
        context: '处置方式会直接改变门岗压力、访客等待时间和审计要求。',
        choices: [
          {
            id: 'guard_override',
            title: '门岗双人核验后临时放行',
            routeLabel: '人工兜底',
            consequence: '通行更快，但必须记录核验人、放行原因和补录状态。',
            answer: '凭证异常时允许门岗双人核验后临时放行，但必须填写原因、关联访客身份，并在当班结束前补齐预约记录。',
            nextStepId: 'aster_operating_roles',
            impactModuleIds: ['roles', 'audit', 'risk'],
          },
          {
            id: 'remote_reverify',
            title: '由接待人远程确认后重发凭证',
            routeLabel: '远程复核',
            consequence: '安全边界更清楚，但需要控制等待时间并处理接待人失联。',
            answer: '凭证异常时由接待人远程确认，系统重新发放短时凭证；超过等待时限再转人工值守负责人处理。',
            nextStepId: 'aster_operating_roles',
            impactModuleIds: ['service_journey', 'roles', 'scope'],
          },
        ],
      },
      aster_permissions: {
        id: 'aster_permissions',
        moduleId: 'roles',
        prompt: '临时放行的最终批准权放在哪里？',
        context: '批准位置决定现场速度，也决定责任是否能被清楚追踪。',
        choices: [
          {
            id: 'security_owner',
            title: '当班安保负责人批准',
            routeLabel: '现场授权',
            consequence: '响应快，但需要明确额度、场景和事后复核规则。',
            answer: '临时放行由当班安保负责人批准，只限预设异常场景，并要求次日由园区运营复核全部记录。',
            nextStepId: 'aster_operating_roles',
            impactModuleIds: ['exception', 'audit', 'risk'],
          },
          {
            id: 'operations_owner',
            title: '园区运营远程批准',
            routeLabel: '集中审批',
            consequence: '责任集中，但必须设置响应时限和超时升级机制。',
            answer: '临时放行由园区运营远程批准，门岗只负责核验；两分钟未响应时自动升级给现场总负责人。',
            nextStepId: 'aster_operating_roles',
            impactModuleIds: ['service_journey', 'exception', 'risk'],
          },
        ],
      },
      aster_audit: {
        id: 'aster_audit',
        moduleId: 'audit',
        prompt: '记录策略更偏向最小留存，还是完整还原现场过程？',
        context: '留存越完整，追责能力越强，同时也会增加权限和隐私管理成本。',
        choices: [
          {
            id: 'minimal_audit',
            title: '保留必要通行结果与异常原因',
            routeLabel: '最小留存',
            consequence: '数据负担较小，但复杂争议可能缺少完整过程证据。',
            answer: '只保留通行结果、异常原因、处理人和时间，普通记录保留九十天，超过期限自动清理。',
            nextStepId: 'aster_operating_roles',
            impactModuleIds: ['roles', 'scope'],
          },
          {
            id: 'full_audit',
            title: '保留完整核验与修改链路',
            routeLabel: '完整追踪',
            consequence: '便于处理争议，但需要更严格的查询权限和留存期限。',
            answer: '保留每次核验、修改、人工放行和复核动作，查询仅开放给授权运营和安全负责人，并按事件等级设置保留期。',
            nextStepId: 'aster_operating_roles',
            impactModuleIds: ['roles', 'risk', 'exception'],
          },
        ],
      },
      aster_operating_roles: {
        id: 'aster_operating_roles',
        moduleId: 'roles',
        prompt: '峰会当天，现场处置与事后复核怎样分工？',
        context: '同一个人既处置又复核会更快，但难以形成清楚的责任制衡。',
        choices: [
          {
            id: 'separate_duty',
            title: '当班处置，次日独立复核',
            routeLabel: '处置复核分离',
            consequence: '现场响应不会被拖慢，同时保留独立检查和问题回溯。',
            answer: '当班安保负责现场处置，园区运营在次日独立复核放行理由、补录状态和异常证据。',
            nextStepId: 'aster_operating_exception',
            impactModuleIds: ['audit', 'exception', 'risk'],
          },
          {
            id: 'incident_commander',
            title: '设置现场事件负责人',
            routeLabel: '事件负责人',
            consequence: '重大异常决策集中，但必须记录授权范围和交接规则。',
            answer: '峰会期间设置现场事件负责人统一批准重大异常，门岗执行并留痕，换班时逐项交接未闭环事件。',
            nextStepId: 'aster_operating_exception',
            impactModuleIds: ['exception', 'audit', 'risk'],
          },
        ],
      },
      aster_operating_exception: {
        id: 'aster_operating_exception',
        moduleId: 'exception',
        prompt: '门禁设备离线或网络中断时，入口怎样继续？',
        context: '设备故障不能只写“人工处理”，还要明确可用名单、放行边界和恢复后的补录。',
        choices: [
          {
            id: 'offline_roster',
            title: '启用离线名单与补录',
            routeLabel: '离线名单',
            consequence: '入口可继续通行，但名单下发、版本时间和补录责任必须受控。',
            answer: '网络中断时启用当天签名离线名单，双人核验后记录时间和证件尾号，恢复后由当班负责人统一补录。',
            nextStepId: 'aster_operating_audit',
            impactModuleIds: ['roles', 'audit', 'risk'],
          },
          {
            id: 'backup_gate',
            title: '关闭故障入口并引导备用门',
            routeLabel: '备用入口',
            consequence: '安全边界更稳，但要验证引导能力和备用入口峰值容量。',
            answer: '故障入口停止人工放行，访客统一引导到具备独立网络的备用门，并实时广播预计等待时间。',
            nextStepId: 'aster_operating_audit',
            impactModuleIds: ['service_journey', 'scope', 'risk'],
          },
        ],
      },
      aster_operating_audit: {
        id: 'aster_operating_audit',
        moduleId: 'audit',
        prompt: '通行记录的查询范围和留存时间怎样控制？',
        context: '查询权限和保留期限要同时满足争议处理、日常运营和最小必要原则。',
        choices: [
          {
            id: 'tiered_retention',
            title: '普通记录与事件记录分级留存',
            routeLabel: '分级留存',
            consequence: '日常数据负担较小，重大事件仍保留完整证据。',
            answer: '普通通行记录保留九十天，重大事件链路保留一年；查询按运营、安全和审计角色分级授权。',
            nextStepId: 'aster_scope',
            impactModuleIds: ['roles', 'risk', 'report'],
          },
          {
            id: 'case_based_access',
            title: '按事件申请临时查询权限',
            routeLabel: '事件授权查询',
            consequence: '查询边界最清楚，但争议处理会增加审批时间。',
            answer: '日常只展示统计结果，查看个人通行明细必须关联事件单申请，权限到期后自动回收。',
            nextStepId: 'aster_scope',
            impactModuleIds: ['roles', 'risk', 'report'],
          },
        ],
      },
      aster_scope: {
        id: 'aster_scope',
        moduleId: 'scope',
        prompt: '峰会前的首版，上线范围收在哪里最稳妥？',
        context: '范围越大，现场培训、设备验证和异常演练的组合风险越高。',
        choices: [
          {
            id: 'three_gate_core',
            title: '先覆盖三个核心入口',
            routeLabel: '核心入口首版',
            consequence: '能集中验证预约、核验、异常和追踪闭环，再决定是否扩面。',
            answer: '首版只覆盖三个核心入口和峰会访客，包含预约、凭证、异常处置和通行记录，不同时改造园区全部门岗。',
            nextStepId: 'aster_risk',
            impactModuleIds: ['service_journey', 'exception', 'risk'],
          },
          {
            id: 'park_wide_launch',
            title: '峰会前统一改造全部入口',
            routeLabel: '全园区上线',
            consequence: '规则一致，但设备、培训和现场协同必须一次性通过验证。',
            answer: '首版覆盖园区全部入口，统一凭证和异常规则，并在峰会前完成所有班次培训和设备联调。',
            nextStepId: 'aster_risk',
            impactModuleIds: ['roles', 'scope', 'risk'],
          },
        ],
      },
      aster_risk: {
        id: 'aster_risk',
        moduleId: 'risk',
        prompt: '正式上线前，采用哪种现场验证方式？',
        context: '验证方式决定能否提前发现容量、交接和异常兜底中的组合问题。',
        choices: [
          {
            id: 'single_gate_pilot',
            title: '先做单入口试运行',
            routeLabel: '单入口试运行',
            consequence: '能低成本暴露流程问题，但无法完全复现峰会并发压力。',
            answer: '先选一个高流量入口试运行两天，记录等待时间、异常比例和人工介入，再据此调整全场方案。',
            nextStepId: 'aster_report',
            impactModuleIds: ['service_journey', 'scope', 'report'],
          },
          {
            id: 'full_rehearsal',
            title: '组织全流程带压演练',
            routeLabel: '全流程演练',
            consequence: '准备成本更高，但能同时验证设备、人员、引导和升级链路。',
            answer: '峰会前按预计峰值组织全流程演练，包含设备离线、接待人失联和入口拥堵三类故障注入。',
            nextStepId: 'aster_report',
            impactModuleIds: ['exception', 'roles', 'report'],
          },
        ],
      },
      aster_report: {
        id: 'aster_report',
        moduleId: 'report',
        prompt: '本轮报告首先服务哪类使用者？',
        context: '报告用途会决定正文更强调现场动作、管理审批，还是责任追溯。',
        choices: [
          {
            id: 'frontline_manual',
            title: '先形成现场值守手册',
            routeLabel: '值守手册',
            consequence: '执行人员能直接照单操作，管理取舍放入附录。',
            answer: '本轮报告优先生成现场值守手册，正文突出正常流程、异常清单、升级联系人和交接记录。',
            nextStepId: null,
            impactModuleIds: ['service_journey', 'exception', 'roles'],
          },
          {
            id: 'management_review',
            title: '先用于管理审批与问责',
            routeLabel: '管理复核',
            consequence: '责任和风险更清楚，后续还需再转成一线操作版本。',
            answer: '本轮报告优先用于管理审批，正文突出范围取舍、授权边界、风险预案和审计责任。',
            nextStepId: null,
            impactModuleIds: ['scope', 'audit', 'risk'],
          },
        ],
      },
    },
  },
  outsourcing: {
    caseId: 'outsourcing',
    domainLabel: '采购交付 / 合同与验收',
    routeTitle: '官网外包交付控制路线',
    introduction: '同一个官网项目，会因为业务目标不同而改变内容责任、交付物、验收方式和变更成本。',
    completionMessage: '官网采购的首轮关键模块已经形成可复核路线；报告会区分当前约定、报价边界和仍需谈判的事项。',
    startStepId: 'outsourcing_priority',
    steps: {
      outsourcing_priority: {
        id: 'outsourcing_priority',
        moduleId: 'business_goal',
        prompt: '六周后的首版，最优先证明什么价值？',
        context: '目标不同，后续要先确认的责任和验收证据也不同。',
        choices: [
          {
            id: 'lead_conversion',
            title: '先跑通客户线索转化',
            routeLabel: '线索转化',
            consequence: '优先处理表单、通知、归属和跟进时限，内容深度可以后补。',
            answer: '首版最优先证明官网能稳定收集有效线索，并让销售及时接收和跟进；品牌内容先满足可信展示即可。',
            nextStepId: 'outsourcing_leads',
            impactModuleIds: ['lead_flow', 'deliverables', 'acceptance'],
          },
          {
            id: 'brand_trust',
            title: '先建立品牌与案例可信度',
            routeLabel: '品牌内容',
            consequence: '优先确认内容质量和素材责任，线索系统先保持简单。',
            answer: '首版最优先让客户快速理解公司能力和案例可信度，内容结构、案例质量和品牌一致性高于复杂线索功能。',
            nextStepId: 'outsourcing_content',
            impactModuleIds: ['content_scope', 'deliverables', 'change_rule'],
          },
          {
            id: 'deadline_first',
            title: '先确保六周内准时上线',
            routeLabel: '按期上线',
            consequence: '优先冻结首版清单和分阶段验收，减少内容与功能的并行扩张。',
            answer: '首版最优先保证六周内可上线，先冻结必须页面、基础表单和部署交接，其他内容按后续版本处理。',
            nextStepId: 'outsourcing_acceptance',
            impactModuleIds: ['acceptance', 'content_scope', 'change_rule'],
          },
        ],
      },
      outsourcing_leads: {
        id: 'outsourcing_leads',
        moduleId: 'lead_flow',
        prompt: '线索提交后，首版做到哪一层才算闭环？',
        context: '集成深度会显著改变开发工作量、账号交接和验收方式。',
        choices: [
          {
            id: 'mail_notify',
            title: '表单入库并通知负责人',
            routeLabel: '轻量线索闭环',
            consequence: '六周内更稳妥，但销售跟进状态仍在线下管理。',
            answer: '首版做到表单校验、线索入库和邮件通知负责人，销售跟进状态暂不回写官网。',
            nextStepId: 'outsourcing_content_control',
            impactModuleIds: ['deliverables', 'acceptance'],
          },
          {
            id: 'crm_integration',
            title: '直接进入 CRM 并分配销售',
            routeLabel: 'CRM 集成',
            consequence: '闭环更完整，但接口联调、字段映射和账号责任必须进入合同。',
            answer: '首版线索直接写入 CRM，并按地区分配销售；CRM 接口、字段映射和失败重试都列为正式交付物。',
            nextStepId: 'outsourcing_content_control',
            impactModuleIds: ['deliverables', 'acceptance', 'change_rule'],
          },
        ],
      },
      outsourcing_content: {
        id: 'outsourcing_content',
        moduleId: 'content_scope',
        prompt: '内容质量由谁承担最终责任？',
        context: '内容责任不明确，是官网外包最常见的延期和返工来源之一。',
        choices: [
          {
            id: 'client_content',
            title: '甲方提供定稿内容，乙方负责上线',
            routeLabel: '甲方定稿',
            consequence: '报价边界清晰，但需要设置内容提交和延误处理节点。',
            answer: '甲方负责提供定稿文案、图片和案例授权，乙方只负责页面适配与上线；内容延迟会顺延对应里程碑。',
            nextStepId: 'outsourcing_content_control',
            impactModuleIds: ['deliverables', 'acceptance', 'change_rule'],
          },
          {
            id: 'vendor_strategy',
            title: '乙方参与内容策划与改写',
            routeLabel: '联合策划',
            consequence: '最终效果更统一，但审稿轮次和新增内容必须单独计入范围。',
            answer: '乙方负责内容结构和重点文案改写，甲方负责事实确认与最终审批；双方约定两轮集中审稿。',
            nextStepId: 'outsourcing_content_control',
            impactModuleIds: ['deliverables', 'change_rule', 'acceptance'],
          },
        ],
      },
      outsourcing_acceptance: {
        id: 'outsourcing_acceptance',
        moduleId: 'acceptance',
        prompt: '六周上线目标采用哪种验收方式？',
        context: '验收方式会决定付款节点，也会决定未完成内容如何进入后续版本。',
        choices: [
          {
            id: 'checklist_acceptance',
            title: '按冻结清单逐项验收',
            routeLabel: '清单验收',
            consequence: '完成边界明确，适合固定周期，但需要提前冻结页面和功能列表。',
            answer: '按冻结的页面、功能、移动端和部署清单逐项验收，清单之外的调整统一进入变更流程。',
            nextStepId: 'outsourcing_content_control',
            impactModuleIds: ['content_scope', 'deliverables', 'change_rule'],
          },
          {
            id: 'phased_launch',
            title: '先上线核心页面，再分批补齐',
            routeLabel: '分阶段上线',
            consequence: '能守住时间节点，但必须定义每一批的独立验收和付款条件。',
            answer: '六周先上线核心页面和基础线索表单，其余案例与内容分批发布，每一批单独验收并确认付款。',
            nextStepId: 'outsourcing_content_control',
            impactModuleIds: ['content_scope', 'deliverables', 'change_rule'],
          },
        ],
      },
      outsourcing_content_control: {
        id: 'outsourcing_content_control',
        moduleId: 'content_scope',
        prompt: '首版内容如何冻结，才能避免审稿拖垮工期？',
        context: '内容责任之外，还要明确每批提交、谁能定稿，以及逾期如何影响里程碑。',
        choices: [
          {
            id: 'page_owner_freeze',
            title: '每类页面指定一名定稿人',
            routeLabel: '单一内容负责人',
            consequence: '反馈链更短，但甲方内部意见需要先自行合并。',
            answer: '产品、案例和公司页面各指定一名定稿人，乙方只接收合并意见；逾期定稿会顺延对应页面里程碑。',
            nextStepId: 'outsourcing_lead_control',
            impactModuleIds: ['deliverables', 'acceptance', 'change_rule'],
          },
          {
            id: 'batch_content_review',
            title: '按页面批次集中审稿',
            routeLabel: '批次审稿',
            consequence: '多方可以参与，但必须限制每批轮次和反馈窗口。',
            answer: '内容按三批提交，每批保留两轮集中审稿和两个工作日反馈窗口，超出轮次进入变更评估。',
            nextStepId: 'outsourcing_lead_control',
            impactModuleIds: ['acceptance', 'deliverables', 'change_rule'],
          },
        ],
      },
      outsourcing_lead_control: {
        id: 'outsourcing_lead_control',
        moduleId: 'lead_flow',
        prompt: '线索提交失败或无人跟进时，首版怎样兜底？',
        context: '表单“能提交”不等于业务闭环，需要定义失败提醒、责任人和补偿处理。',
        choices: [
          {
            id: 'lead_retry_queue',
            title: '失败重试并进入待处理队列',
            routeLabel: '失败重试队列',
            consequence: '线索不易丢失，但要交付队列监控和人工补发入口。',
            answer: '通知或 CRM 写入失败时自动重试三次，仍失败则进入待处理队列，并在后台提示指定运营负责人。',
            nextStepId: 'outsourcing_acceptance_control',
            impactModuleIds: ['deliverables', 'acceptance', 'report'],
          },
          {
            id: 'lead_confirmation',
            title: '用户确认页并同步人工邮箱',
            routeLabel: '双通道留线索',
            consequence: '实现更稳妥，但销售状态仍需要人工维护。',
            answer: '提交成功后向用户展示确认编号，同时把线索副本发送到公共邮箱；系统异常时可按编号人工核对。',
            nextStepId: 'outsourcing_acceptance_control',
            impactModuleIds: ['content_scope', 'deliverables', 'acceptance'],
          },
        ],
      },
      outsourcing_acceptance_control: {
        id: 'outsourcing_acceptance_control',
        moduleId: 'acceptance',
        prompt: '验收发现问题后，怎样区分缺陷、遗漏和新增需求？',
        context: '分类口径会直接决定免费修复、延期责任和新增报价。',
        choices: [
          {
            id: 'evidence_based_acceptance',
            title: '按验收证据分类处理',
            routeLabel: '证据化验收',
            consequence: '争议更少，但合同前需要把页面、状态和验证方式写细。',
            answer: '与冻结清单或验收用例不符的算缺陷，清单内漏做算遗漏，改变已确认行为或新增内容才进入变更。',
            nextStepId: 'outsourcing_deliverables',
            impactModuleIds: ['deliverables', 'change_rule', 'report'],
          },
          {
            id: 'joint_triage',
            title: '每周联合评审问题清单',
            routeLabel: '联合问题评审',
            consequence: '适合边做边确认，但需要明确谁有最终分类权。',
            answer: '双方每周联合评审问题清单，由甲方项目负责人和乙方交付负责人共同确认缺陷、遗漏或变更类别。',
            nextStepId: 'outsourcing_deliverables',
            impactModuleIds: ['content_scope', 'change_rule', 'report'],
          },
        ],
      },
      outsourcing_deliverables: {
        id: 'outsourcing_deliverables',
        moduleId: 'deliverables',
        prompt: '项目结束时，哪些成果必须可由甲方独立接管？',
        context: '页面上线不是完整交付，账号、源码、素材授权和部署说明会决定后续是否被供应商锁定。',
        choices: [
          {
            id: 'full_handover',
            title: '源码、账号和部署完整移交',
            routeLabel: '完整技术移交',
            consequence: '甲方可独立维护，但交接清单和培训会增加首期成本。',
            answer: '交付源码仓库、设计源文件、域名和部署账号、素材授权、环境说明及一次接管培训，账号均转为甲方所有。',
            nextStepId: 'outsourcing_change_rule',
            impactModuleIds: ['acceptance', 'change_rule', 'report'],
          },
          {
            id: 'managed_delivery',
            title: '由乙方托管并承诺可迁移',
            routeLabel: '托管交付',
            consequence: '上线更省心，但迁移条件、数据导出和服务终止必须写入合同。',
            answer: '乙方负责一年托管运维，同时交付数据导出说明、迁移包格式和服务终止后的账号与源码移交时限。',
            nextStepId: 'outsourcing_change_rule',
            impactModuleIds: ['acceptance', 'change_rule', 'report'],
          },
        ],
      },
      outsourcing_change_rule: {
        id: 'outsourcing_change_rule',
        moduleId: 'change_rule',
        prompt: '六周内需求变化采用哪种控制方式？',
        context: '固定轮次适合守住范围，滚动清单适合快速响应，但两者的费用和进度承诺不同。',
        choices: [
          {
            id: 'fixed_revision_rounds',
            title: '两轮免费调整，超出单独报价',
            routeLabel: '固定修改轮次',
            consequence: '合同边界清楚，但甲方需要在每轮前合并完整意见。',
            answer: '每批内容和页面包含两轮合并调整，超出轮次或改变冻结范围时先评估工期与费用，再书面确认。',
            nextStepId: 'outsourcing_report',
            impactModuleIds: ['content_scope', 'acceptance', 'report'],
          },
          {
            id: 'weekly_budget_cap',
            title: '每周滚动清单并设置费用上限',
            routeLabel: '滚动预算控制',
            consequence: '响应更灵活，但每周都要重新排序，固定上线清单会更小。',
            answer: '需求进入每周滚动清单，在总预算上限内按优先级置换；新增内容必须同时移出等量工作或追加预算。',
            nextStepId: 'outsourcing_report',
            impactModuleIds: ['business_goal', 'content_scope', 'acceptance'],
          },
        ],
      },
      outsourcing_report: {
        id: 'outsourcing_report',
        moduleId: 'report',
        prompt: '本轮报告首先用于哪一个采购动作？',
        context: '内部立项与合同附件需要的颗粒度不同，报告应先服务最近的决策。',
        choices: [
          {
            id: 'vendor_comparison',
            title: '用于多家供应商比价',
            routeLabel: '询价说明书',
            consequence: '重点是统一报价口径，法律条款仍需后续补充。',
            answer: '本轮报告先作为供应商询价说明书，统一业务目标、首版范围、交付物、里程碑和报价假设。',
            nextStepId: null,
            impactModuleIds: ['business_goal', 'deliverables', 'acceptance'],
          },
          {
            id: 'contract_appendix',
            title: '直接形成合同需求附件',
            routeLabel: '合同附件',
            consequence: '边界更可执行，但知识产权、付款和违约条款需要同步审查。',
            answer: '本轮报告按合同附件整理，重点明确交付清单、验收证据、变更规则、账号归属和问题修复责任。',
            nextStepId: null,
            impactModuleIds: ['deliverables', 'acceptance', 'change_rule'],
          },
        ],
      },
    },
  },
  capstone: {
    caseId: 'capstone',
    domainLabel: '学生项目 / AI 可靠性与答辩',
    routeTitle: '智能面试助手答辩保障路线',
    introduction: '毕业设计既要展示 AI 能力，也要控制模型不稳定、评分误导和多人协作风险。',
    completionMessage: '毕业设计的首轮关键模块已经形成可复核路线；报告会同时保留演示结论、技术边界和仍需验证的风险。',
    startStepId: 'capstone_priority',
    steps: {
      capstone_priority: {
        id: 'capstone_priority',
        moduleId: 'success_criteria',
        prompt: '答辩现场最不能失败的是哪一部分？',
        context: '这个选择会决定团队先投入模型兜底、评分证据，还是现场演示能力。',
        choices: [
          {
            id: 'demo_stability',
            title: '演示闭环必须稳定跑完',
            routeLabel: '演示稳定',
            consequence: '优先处理模型故障兜底、依赖责任和离线演示数据。',
            answer: '答辩现场最不能失败的是完整演示闭环。即使模型接口异常，也必须能完成模拟面试、记录和反馈展示。',
            nextStepId: 'capstone_fallback',
            impactModuleIds: ['team_dependency', 'demo_flow', 'schedule'],
          },
          {
            id: 'score_explainability',
            title: '评分必须讲得清依据',
            routeLabel: '评分证据',
            consequence: '优先建立评分维度、证据引用和模型输出边界。',
            answer: '答辩现场最不能失败的是评分无法解释。每个分数必须对应明确维度、回答证据和可复述的改进建议。',
            nextStepId: 'capstone_scoring',
            impactModuleIds: ['scoring', 'privacy', 'report'],
          },
          {
            id: 'innovation_demo',
            title: '创新点必须被现场看见',
            routeLabel: '创新展示',
            consequence: '优先设计可对比的现场输入和结果，同时控制不可预测性。',
            answer: '答辩现场最不能失败的是创新点没有被看见。需要让评委直观看到不同回答如何产生不同追问和反馈。',
            nextStepId: 'capstone_live_demo',
            impactModuleIds: ['demo_flow', 'scoring', 'team_dependency'],
          },
        ],
      },
      capstone_fallback: {
        id: 'capstone_fallback',
        moduleId: 'team_dependency',
        prompt: '模型接口异常时，演示如何继续？',
        context: '兜底方案会改变数据准备、前后端责任和答辩说明。',
        choices: [
          {
            id: 'local_fixture',
            title: '切换到本地预置案例',
            routeLabel: '本地兜底',
            consequence: '稳定性最高，但答辩时要清楚说明真实模型与预置结果的边界。',
            answer: '模型接口异常时自动切换到本地预置案例，保留相同页面流程，并在答辩说明中明确这是故障兜底。',
            nextStepId: 'capstone_demo_flow',
            impactModuleIds: ['demo_flow', 'privacy', 'report'],
          },
          {
            id: 'cloud_retry',
            title: '主模型重试并切换备用模型',
            routeLabel: '双模型切换',
            consequence: '更接近真实系统，但团队需要负责超时、成本和结果差异。',
            answer: '主模型超时后重试一次，再切换备用模型；超过总等待时限就停止生成并展示可解释的失败状态。',
            nextStepId: 'capstone_demo_flow',
            impactModuleIds: ['schedule', 'privacy', 'report'],
          },
        ],
      },
      capstone_scoring: {
        id: 'capstone_scoring',
        moduleId: 'scoring',
        prompt: '评分依据采用哪种组合？',
        context: '评分越依赖模型自由判断，越需要解释不确定性和误用风险。',
        choices: [
          {
            id: 'rubric_plus_model',
            title: '固定量表评分，模型负责解释',
            routeLabel: '量表 + 解释',
            consequence: '评分口径稳定，创新性略弱，但更适合答辩和复现。',
            answer: '先按固定量表计算维度得分，模型只负责引用回答证据并生成解释，不直接改变量表权重。',
            nextStepId: 'capstone_demo_flow',
            impactModuleIds: ['demo_flow', 'report', 'privacy'],
          },
          {
            id: 'model_judgement',
            title: '模型综合判断并给出证据',
            routeLabel: '模型综合评分',
            consequence: '展示效果更灵活，但必须说明波动、偏差和不可作为招聘结论。',
            answer: '由模型综合判断并引用回答片段，但同时展示评分置信度、可能偏差，并明确结果只用于练习反馈。',
            nextStepId: 'capstone_demo_flow',
            impactModuleIds: ['privacy', 'report', 'demo_flow'],
          },
        ],
      },
      capstone_live_demo: {
        id: 'capstone_live_demo',
        moduleId: 'demo_flow',
        prompt: '现场展示采用固定案例，还是接受评委临时输入？',
        context: '开放程度越高，创新感越强，同时也会增加模型和内容安全风险。',
        choices: [
          {
            id: 'guided_live',
            title: '固定主案例，增加一个可控现场输入',
            routeLabel: '可控现场演示',
            consequence: '兼顾稳定和互动，团队可以提前准备边界与失败处理。',
            answer: '先用固定主案例完整展示，再允许评委输入一个限定长度的问题，出现异常时回到主案例继续说明。',
            nextStepId: 'capstone_demo_flow',
            impactModuleIds: ['team_dependency', 'privacy', 'schedule'],
          },
          {
            id: 'fully_live',
            title: '全程接受现场自由输入',
            routeLabel: '全现场输入',
            consequence: '创新展示更强，但需要内容过滤、超时和无法生成时的说明方案。',
            answer: '现场允许自由输入，但限制内容长度，并准备超时、内容不适合和模型失败三类可解释状态。',
            nextStepId: 'capstone_demo_flow',
            impactModuleIds: ['team_dependency', 'privacy', 'report'],
          },
        ],
      },
      capstone_demo_flow: {
        id: 'capstone_demo_flow',
        moduleId: 'demo_flow',
        prompt: '完整答辩演示采用怎样的主线和恢复点？',
        context: '演示脚本既要让创新点被看见，也要能在任一步骤失败后继续讲清楚。',
        choices: [
          {
            id: 'checkpoint_demo',
            title: '按三个检查点分段演示',
            routeLabel: '分段检查点',
            consequence: '任何一段失败都能从下一检查点继续，现场叙事更稳定。',
            answer: '演示分为问题生成、模拟回答和评分反馈三个检查点，每段准备可恢复状态，并保存上一段结果。',
            nextStepId: 'capstone_scoring_control',
            impactModuleIds: ['team_dependency', 'schedule', 'report'],
          },
          {
            id: 'single_story_demo',
            title: '围绕一名候选人完整演示',
            routeLabel: '单案例主线',
            consequence: '故事更连贯，但中途失败会影响后续全部环节。',
            answer: '答辩围绕一名模拟候选人完成岗位选择、追问、评分和改进建议，关键页面保留截图作为恢复依据。',
            nextStepId: 'capstone_scoring_control',
            impactModuleIds: ['scoring', 'privacy', 'schedule'],
          },
        ],
      },
      capstone_scoring_control: {
        id: 'capstone_scoring_control',
        moduleId: 'scoring',
        prompt: '怎样证明评分不是一次偶然的模型输出？',
        context: '可解释不仅要展示理由，还要用固定材料说明同类输入的结果是否稳定。',
        choices: [
          {
            id: 'benchmark_set',
            title: '准备固定基准回答集',
            routeLabel: '基准样例验证',
            consequence: '结果可复现，适合答辩说明，但覆盖范围有限。',
            answer: '准备高、中、低三档固定回答集，记录评分维度、引用证据和多次运行波动，用于展示评分稳定性。',
            nextStepId: 'capstone_team_delivery',
            impactModuleIds: ['demo_flow', 'privacy', 'report'],
          },
          {
            id: 'human_review_sample',
            title: '抽样与人工评分对照',
            routeLabel: '人工对照验证',
            consequence: '说服力更强，但需要统一人工量表和记录分歧。',
            answer: '抽取二十条模拟回答，由两名成员独立评分，再与系统结果对照并说明一致、分歧和不可下结论的部分。',
            nextStepId: 'capstone_team_delivery',
            impactModuleIds: ['team_dependency', 'privacy', 'report'],
          },
        ],
      },
      capstone_team_delivery: {
        id: 'capstone_team_delivery',
        moduleId: 'team_dependency',
        prompt: '三名成员如何划分最终可验收的交付责任？',
        context: '只写“前端、后端、模型”仍会留下接口联调、数据准备和答辩材料的空档。',
        choices: [
          {
            id: 'artifact_ownership',
            title: '按成果物指定唯一负责人',
            routeLabel: '成果物负责制',
            consequence: '责任清楚，但每个负责人还要主动协调依赖。',
            answer: '界面与演示包、服务与数据、模型与评测、答辩材料分别指定唯一负责人，并列出交付日期和复核人。',
            nextStepId: 'capstone_privacy',
            impactModuleIds: ['demo_flow', 'schedule', 'report'],
          },
          {
            id: 'integration_owner',
            title: '设置一名集成负责人',
            routeLabel: '集成负责人',
            consequence: '联调决策集中，但要避免集成工作全部压在一人身上。',
            answer: '每人保留专业模块责任，同时轮值一名集成负责人维护接口清单、每日构建和故障记录。',
            nextStepId: 'capstone_privacy',
            impactModuleIds: ['demo_flow', 'scoring', 'schedule'],
          },
        ],
      },
      capstone_privacy: {
        id: 'capstone_privacy',
        moduleId: 'privacy',
        prompt: '演示数据和现场输入采用哪种处理边界？',
        context: '答辩演示不应把真实求职者信息、录音或敏感判断带入不可控的模型链路。',
        choices: [
          {
            id: 'synthetic_only',
            title: '只使用模拟与脱敏数据',
            routeLabel: '模拟数据演示',
            consequence: '风险最低、最易复现，但真实场景说服力需要额外说明。',
            answer: '演示只使用团队编写的模拟岗位和回答，不上传真实简历或录音，并在界面标明数据为教学演示。',
            nextStepId: 'capstone_schedule',
            impactModuleIds: ['demo_flow', 'scoring', 'report'],
          },
          {
            id: 'ephemeral_session',
            title: '现场输入仅在会话内临时保存',
            routeLabel: '临时会话数据',
            consequence: '互动更真实，但要明确同意、删除时点和模型服务边界。',
            answer: '现场输入前展示用途说明并取得同意，内容只保留到本次演示结束，随后自动删除且不进入训练数据。',
            nextStepId: 'capstone_schedule',
            impactModuleIds: ['demo_flow', 'team_dependency', 'report'],
          },
        ],
      },
      capstone_schedule: {
        id: 'capstone_schedule',
        moduleId: 'schedule',
        prompt: '答辩前怎样冻结版本，既守住稳定性又不阻断创新？',
        context: '没有冻结规则时，最后一周的新功能最容易破坏已经验证的主流程。',
        choices: [
          {
            id: 'one_week_freeze',
            title: '提前一周冻结全部功能',
            routeLabel: '一周功能冻结',
            consequence: '稳定性最高，但最后阶段只能修复明确缺陷。',
            answer: '答辩前七天冻结功能和数据格式，之后只处理阻断演示的缺陷，并每天完成一次完整演练。',
            nextStepId: 'capstone_report',
            impactModuleIds: ['demo_flow', 'team_dependency', 'report'],
          },
          {
            id: 'stable_main_branch',
            title: '冻结主线，创新功能单独隔离',
            routeLabel: '主线冻结',
            consequence: '可继续探索创新，但现场是否启用必须有清楚门槛。',
            answer: '主演示分支提前一周冻结，创新功能留在独立分支；只有通过完整回归后才作为可选加演内容。',
            nextStepId: 'capstone_report',
            impactModuleIds: ['demo_flow', 'scoring', 'team_dependency'],
          },
        ],
      },
      capstone_report: {
        id: 'capstone_report',
        moduleId: 'report',
        prompt: '本轮报告首先支撑答辩展示，还是技术审查？',
        context: '两类材料都需要，但主报告应先服务最近且最关键的评审场景。',
        choices: [
          {
            id: 'defense_story',
            title: '先形成答辩叙事与证据',
            routeLabel: '答辩证据包',
            consequence: '评委更容易理解价值，技术细节进入附录。',
            answer: '本轮报告优先形成问题、方案、演示路径、评分证据和风险边界，供答辩讲述与追问准备。',
            nextStepId: null,
            impactModuleIds: ['success_criteria', 'demo_flow', 'scoring'],
          },
          {
            id: 'technical_review',
            title: '先形成技术复现与审查材料',
            routeLabel: '技术审查包',
            consequence: '工程可信度更强，后续还需压缩成答辩主线。',
            answer: '本轮报告优先记录架构、数据边界、评测方法、故障兜底、版本冻结和复现步骤。',
            nextStepId: null,
            impactModuleIds: ['privacy', 'team_dependency', 'schedule'],
          },
        ],
      },
    },
  },
};

export function getFormalDemoBranchScenario(sourceCaseId?: string | null): FormalDemoBranchScenario | null {
  if (!sourceCaseId || !(sourceCaseId in FORMAL_DEMO_BRANCH_SCENARIOS)) return null;
  return FORMAL_DEMO_BRANCH_SCENARIOS[sourceCaseId as FormalDemoBranchCaseId];
}

export function listFormalDemoBranchScenarios(): FormalDemoBranchScenario[] {
  return Object.values(FORMAL_DEMO_BRANCH_SCENARIOS);
}
